# Numpy Tutorial
Numpy = Numerical Python
Advantages of Numpy Arrays:
* Allows several mathematical operations
* Faster Operations

# Chapter 1: Importing the Numpy module

In [1]:
import numpy as np

# Chapter 2: Time Taken

In [2]:
from time import process_time

## Time taken by the list

In [3]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print("Time taken by the lists: ", end_time - start_time)

Time taken by the lists:  0.0009517509999996676


## Time taken by the numpy array

In [4]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array = np_array + 5 # np_array += 5
end_time = process_time()
print("Time taken by numpy arrays: ", end_time - start_time)

Time taken by numpy arrays:  0.0014097780000001947


# Chapter 3: Numpy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list)

[1, 2, 3, 4, 5]


type

In [6]:
# numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

## Creating a One dimensional Array

In [7]:
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

## Creating a Two Dimensional Array

In [8]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

## Creating Float Array

In [9]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype = float)
print(c)
c.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

# Chapter 4: Initial Placeholders in Numpy Arrays
In some cases, we need to initialise an array who have the intial values as 0 or 1 or any other values.

`shape_of_the_array = (rows, columns)`

**Syntax:** 
```
variableName = np.zeros((shape_of_the_array))
variableName = np.ones((shape_of_the_array))
variableName = np.full((shape_of_the_array), value_you_need)
```

**Syntax of Identity Matrix :**
As in identity matrix the `rows = columns`. So, `value = rows = colums`
```
variableName = np.eye(values)
```

**Creating an array with random values :**
In this array will give the array of the numbers in between 0s and 1s
```
variableName = np.random.random((shape_of_an_array))
```

**Creating an array with random integers values :**
```
c = np.random.randint(lower_bound,upper_bound,(rows,columns))
```

In [10]:
# Create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# Create a numpy array if Ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# Create an array of particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
# Create an Identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# Create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.39021591 0.01585506 0.42021056 0.02068124]
 [0.51855902 0.85983745 0.88595191 0.98138188]
 [0.52932012 0.68525815 0.66158852 0.15092422]]


In [15]:
# Create a numpy array with random values but in integers within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[15 94 95 14 97]
 [67 98 49 14 41]
 [85 63 16 36 25]]


In [16]:
# Creating an array of evenly spaced values 
# Specifying the number of values required
d = np.linspace(10,30,5)
e = np.linspace(10,30,6)
print(d)
print(e)

[10. 15. 20. 25. 30.]
[10. 14. 18. 22. 26. 30.]


In [17]:
# Creating an array of evenly spaced values 
# Specifying the step
f = np.arange(10,30,5)
print(f)

[10 15 20 25]


# Chapter 5: Converting List to Numpy Arrays

In [18]:
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

# Chapter 6: Analysing the Numpy Array

In [19]:
c = np.random.randint(10,90,(5,5))
print(c)

[[47 30 28 51 82]
 [34 61 36 21 70]
 [57 46 60 16 89]
 [10 25 64 86 23]
 [27 44 45 74 30]]


In [20]:
# Finding the Array Dimension
print("Shape of the Array: ", c.shape)

# Number of Dimensions
print("Dimension of the Array: ", c.ndim)

# Number of the elements in an array
print("Number of elements in array: ", c.size)

# Checking the datatype of the values in the array
print("Datatype of the values in array is: ", c.dtype)

Shape of the Array:  (5, 5)
Dimension of the Array:  2
Number of elements in array:  25
Datatype of the values in array is:  int64


## Chapter 7: Mathematical Operations on Numpy Array

In [21]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

# concatenate or joins the two lists
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print("The first array is: ")
print(a)
print("The second array is: ")
print(b)
print("Addition of two arrays are: ")
print(a+b)
print("Difference of two arrays are: ")
print(a-b)
print("Product of two arrays are: ")
print(a*b)
print("Division of two arrays are: ")
print(a/b)

The first array is: 
[[6 2 9]
 [1 0 1]
 [1 5 8]]
The second array is: 
[[10 12 17]
 [12 14 16]
 [10 12 19]]
Addition of two arrays are: 
[[16 14 26]
 [13 14 17]
 [11 17 27]]
Difference of two arrays are: 
[[ -4 -10  -8]
 [-11 -14 -15]
 [ -9  -7 -11]]
Product of two arrays are: 
[[ 60  24 153]
 [ 12   0  16]
 [ 10  60 152]]
Division of two arrays are: 
[[0.6        0.16666667 0.52941176]
 [0.08333333 0.         0.0625    ]
 [0.1        0.41666667 0.42105263]]


In [23]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print("The first array is: ")
print(a)
print("The second array is: ")
print(b)
print("Addition of two arrays are: ")
print(np.add(a,b))
print("Difference of two arrays are: ")
print(np.subtract(a,b))
print("Product of two arrays are: ")
print(np.multiply(a,b))
print("Division of two arrays are: ")
print(np.divide(a,b))

The first array is: 
[[6 0 1]
 [6 9 8]
 [9 5 9]]
The second array is: 
[[10 10 13]
 [11 15 16]
 [16 10 10]]
Addition of two arrays are: 
[[16 10 14]
 [17 24 24]
 [25 15 19]]
Difference of two arrays are: 
[[ -4 -10 -12]
 [ -5  -6  -8]
 [ -7  -5  -1]]
Product of two arrays are: 
[[ 60   0  13]
 [ 66 135 128]
 [144  50  90]]
Division of two arrays are: 
[[0.6        0.         0.07692308]
 [0.54545455 0.6        0.5       ]
 [0.5625     0.5        0.9       ]]


# Chapter 8: Array Manipulation


## Transpose of an Array

In [24]:
array = np.random.randint(0,10,(2,3))
print("Displaying the Array: ")
print(array)
print("Shape of the Array: ")
print(array.shape)
print("Transpose of the Array: ")
trans = np.transpose(array)
print(trans)
print("Shape of the Transpose Array: ")
print(trans.shape)
print("Another method of Transpose of the array")
trans2 = array.T
print(trans2)
print("Shape of the Transpose Array: ")
print(trans2.shape)

Displaying the Array: 
[[5 1 0]
 [7 4 0]]
Shape of the Array: 
(2, 3)
Transpose of the Array: 
[[5 7]
 [1 4]
 [0 0]]
Shape of the Transpose Array: 
(3, 2)
Another method of Transpose of the array
[[5 7]
 [1 4]
 [0 0]]
Shape of the Transpose Array: 
(3, 2)


## Reshaping of the Array

In [25]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 9 5]
 [5 2 6]]
(2, 3)


In [26]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 9]
 [5 5]
 [2 6]]
(3, 2)
