## **Numpy Tricks**

In [17]:
import numpy as np
import random

## **Chapter 1:** `np.sort`

Return a sorted copy of an array.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.sort.html)

In [3]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)
print("Array A: ")
print(a)
print()
print("Array B:")
print(b)

Array A: 
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]

Array B:
[[50 55 76  5]
 [46 29 14 16]
 [23 13 50  2]
 [81 87 97 67]
 [14 97 78 79]
 [97 35 79 21]]


In [5]:
print("Sorted Array (1D Array): ")
print(np.sort(a))

Sorted Array: 
[ 1 16 17 19 35 44 75 77 83 84 88 88 92 95 99]


In [9]:
print("Sorted Array (2D Array) Row Sorting: ")
print(np.sort(b, axis = 1)) # Row Sorting

print()

print("Sorted Array (2D Array) Column Sorting: ")
print(np.sort(b, axis = 0)) # Column Sorting

Sorted Array (2D Array) Row Sorting: 
[[ 5 50 55 76]
 [14 16 29 46]
 [ 2 13 23 50]
 [67 81 87 97]
 [14 78 79 97]
 [21 35 79 97]]

Sorted Array (2D Array) Column Sorting: 
[[14 13 14  2]
 [23 29 50  5]
 [46 35 76 16]
 [50 55 78 21]
 [81 87 79 67]
 [97 97 97 79]]


In [10]:
print("Sorting in Descending Order: (1 Dimensional Array)")
print(np.sort(a)[::-1])

Sorting in Descending Order: (1 Dimensional Array)
[99 95 92 88 88 84 83 77 75 44 35 19 17 16  1]


## **Chapter 2:** `np.append`

The numpy.append() appends values along the mentioned axis at the end of the array

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.append.html)

In [11]:
print("Appending in 1 Dimensional Array: ")
print(np.append(a,200))

Appending in 1 Dimensional Array: 
[ 44  95  83  17  99  84  75  16  19  77   1  35  92  88  88 200]


In [19]:
print("Appending in 2 Dimensional Array (Values = 1): ")
# Adding a column that can have only 1s
print(np.append(b, np.ones((b.shape[0], 1)), axis = 1))
print()
print("Appending in 2 Dimensional Array (Values = Random): ")
# Adding a column that can have only random values
print(np.append(b, np.random.random((b.shape[0], 1)), axis = 1))

Appending in 2 Dimensional Array (Values = 1): 
[[50. 55. 76.  5.  1.]
 [46. 29. 14. 16.  1.]
 [23. 13. 50.  2.  1.]
 [81. 87. 97. 67.  1.]
 [14. 97. 78. 79.  1.]
 [97. 35. 79. 21.  1.]]

Appending in 2 Dimensional Array (Values = Random): 
[[50.         55.         76.          5.          0.7642639 ]
 [46.         29.         14.         16.          0.97559091]
 [23.         13.         50.          2.          0.90253829]
 [81.         87.         97.         67.          0.82145837]
 [14.         97.         78.         79.          0.40568132]
 [97.         35.         79.         21.          0.77987487]]


## **Chapter 3:** `np.concatenate`

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)

In [20]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print("Array C: ")
print(c)
print()
print("Array D: ")
print(d)

Array C: 
[[0 1 2]
 [3 4 5]]

Array D: 
[[ 6  7  8]
 [ 9 10 11]]


In [21]:
print("Concatenating Row Wise: ")
print(np.concatenate((c,d), axis = 0)) # Row wise Concatenate

Concatenating Row Wise: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [22]:
print("Concatenating Column Wise: ")
print(np.concatenate((c,d), axis = 1)) # Column Wise Concatenate

Concatenating Column Wise: 
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


## **Chapter 4:** `np.unique`

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.unique.html/)

In [23]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
print("Original Array: ")
print(e)
print()
print("Array containing unique values: ")
print(np.unique(e))

Original Array: 
[1 1 2 2 3 3 4 4 5 5 6 6]

Array containing unique values: 
[1 2 3 4 5 6]


## **Chapter 5:** `np.expand_dims`

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html)

In [28]:
print("Original Array: ", a)
print("Shape of the Array A: ", a.shape)

Original Array:  [44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]
Shape of the Array A:  (15,)


In [29]:
print("After Expanding the Array A (Row Wise): ")
a1 = np.expand_dims(a, axis = 0)
print(a1)
print()
print("Shape of the Array A: ", a1.shape)

After Expanding the Array A (Row Wise): 
[[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]]

Shape of the Array A:  (1, 15)


In [30]:
print("After Expanding the Array A (Column Wise): ")
a2 = np.expand_dims(a, axis = 1)
print(a2)
print()
print("Shape of the Array A: ", a2.shape)

After Expanding the Array A (Column Wise): 
[[44]
 [95]
 [83]
 [17]
 [99]
 [84]
 [75]
 [16]
 [19]
 [77]
 [ 1]
 [35]
 [92]
 [88]
 [88]]

Shape of the Array A:  (15, 1)


## **Chapter 6:** `np.where`

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

```
np.where(condition, true, false)
```

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [31]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [33]:
# Find all indices with value greater than 50
a3 = np.where(a > 50)
print(a3)

(array([ 1,  2,  4,  5,  6,  9, 12, 13, 14]),)


In [34]:
# Replace all values > 50 with 0
print(np.where(a > 50, 0, a))

[44  0  0 17  0  0  0 16 19  0  1 35  0  0  0]


In [35]:
# Replace all Even values with 0
print(np.where(a%2==0, 0, a))

[ 0 95 83 17 99  0 75  0 19 77  1 35  0  0  0]


## **Chapter 7:** `np.argmax`

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)

In [36]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [37]:
print("Returning index of the maximum element: ")
print(np.argmax(a))

Returning index of the maximum element: 
4


In [38]:
print("Original Array:")
print(b)

Original Array:
[[50 55 76  5]
 [46 29 14 16]
 [23 13 50  2]
 [81 87 97 67]
 [14 97 78 79]
 [97 35 79 21]]


In [56]:
print("Returning index of the maximum element (Column Wise): ")
print(np.argmax(b, axis = 0))

Returning index of the maximum element (Column Wise): 
[5 4 3 4]


In [41]:
print("Returning index of the maximum element (Row Wise): ")
print(np.argmax(b, axis = 1))

Returning index of the maximum element (Row Wise): 
[2 0 2 2 1 0]


In [43]:
# np.argmin
print("Returning index of the minimum element: ")
np.argmin(a)

Returning index of the minimum element: 


10

## **Chapter 8:** `np.cumsum`

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html)

In [44]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [48]:
print("Original Array:")
print(b)

Original Array:
[[50 55 76  5]
 [46 29 14 16]
 [23 13 50  2]
 [81 87 97 67]
 [14 97 78 79]
 [97 35 79 21]]


In [45]:
print("Cumulative Summation of 1D Array")
print(np.cumsum(a))

Cumulative Summation of 1D Array
[ 44 139 222 239 338 422 497 513 532 609 610 645 737 825 913]


In [46]:
print("Cumulative Summation of 2D Array: (Column Wise)")
print(np.cumsum(b, axis = 0))

Cumulative Summation of 2D Array
[[ 50  55  76   5]
 [ 96  84  90  21]
 [119  97 140  23]
 [200 184 237  90]
 [214 281 315 169]
 [311 316 394 190]]


In [57]:
print("Cumulative Summation of 2D Array: (Row Wise)")
print(np.cumsum(b, axis = 1))

Cumulative Summation of 2D Array: (Row Wise)
[[ 50 105 181 186]
 [ 46  75  89 105]
 [ 23  36  86  88]
 [ 81 168 265 332]
 [ 14 111 189 268]
 [ 97 132 211 232]]


## **Chapter 9:** `np.percentile`

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html)

In [49]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [58]:
print("Percentile of an Array:")
print(np.percentile(a, 100))

Percentile of an Array:
99.0


In [59]:
print("Percentile of an Array:")
print(np.percentile(a, 0))

Percentile of an Array:
1.0


In [60]:
print("Percentile of an Array:")
print(np.percentile(a, 50)) # This will be equal to median

Percentile of an Array:
77.0


In [53]:
print("Median of an Array:")
print(np.median(a))

Median of an Array:
77.0


## **Chapter 10:** `np.histogram`

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html)

In [54]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [61]:
print(np.histogram(a,bins=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ]))

(array([3, 0, 1, 1, 0, 0, 2, 4, 3]), array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [62]:
print(np.histogram(a,bins=[0,50,100]))
# 0 to 50 : 6
# 50 to 100: 9

(array([6, 9]), array([  0,  50, 100]))


## **Chapter 11:** `numpy.isin()`

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

Inshort, it used to search multiple items in a array in one go.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.isin.html)

In [65]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [66]:
items = [10,20,30,40,50,60,70,80,90,100]
print("Searching items in original array: ")
print(np.isin(a,items))

Searching items in original array: 
[False False False False False False False False False False False False
 False False False]


In [67]:
items = [44,55,66,77,99,88,100,1,2,3]
print("Searching items in original array: ")
print(np.isin(a,items))

Searching items in original array: 
[ True False False False  True False False False False  True  True False
 False  True  True]


## **Chapter 12:** `numpy.flip()`

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

Inshort, it will be a mirror image

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.flip.html)

In [68]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [73]:
print("Reversed Array (1 Dimensional):")
print(np.flip(a)) # Mirror Image

Reversed Array (1 Dimensional):
[88 88 92 35  1 77 19 16 75 84 99 17 83 95 44]


In [70]:
print("Original Array:")
print(b)

Original Array:
[[50 55 76  5]
 [46 29 14 16]
 [23 13 50  2]
 [81 87 97 67]
 [14 97 78 79]
 [97 35 79 21]]


In [74]:
print("Reversed Array (Both Row and Column Wise):")
print(np.flip(b))

Reversed Array (Both Row and Column Wise):
[[21 79 35 97]
 [79 78 97 14]
 [67 97 87 81]
 [ 2 50 13 23]
 [16 14 29 46]
 [ 5 76 55 50]]


In [71]:
print("Reversed Array (Column Wise):")
print(np.flip(b,axis = 0)) # Mirror Image

Reversed Array (Column Wise):
[[97 35 79 21]
 [14 97 78 79]
 [81 87 97 67]
 [23 13 50  2]
 [46 29 14 16]
 [50 55 76  5]]


In [72]:
print("Reversed Array (Row wise):")
print(np.flip(b, axis = 1)) # Mirror Image

Reversed Array (Row wise):
[[ 5 76 55 50]
 [16 14 29 46]
 [ 2 50 13 23]
 [67 97 87 81]
 [79 78 97 14]
 [21 79 35 97]]


## **Chapter 13:** `numpy.put()`

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

Inshort, it change.

```
np.put(array_name, [indexes_you_wanna_change], [values_you_wanna_replace])
```


[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.put.html)

In [75]:
print("Original Array:")
print(a)

Original Array:
[44 95 83 17 99 84 75 16 19 77  1 35 92 88 88]


In [78]:
print(" ----------------- Changing the Original Array Using np.put() ----------------- ")
np.put(a,[0,1], [100, 500]) # permanent changes
print("Changed Array: ")
print(a)

 ----------------- Changing the Original Array Using np.put() ----------------- 
Changed Array: 
[100 500  83  17  99  84  75  16  19  77   1  35  92  88  88]


## **Chapter 14:** `numpy.delete()`

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

```
np.delete(array_name, index_you_wanna_delete)
```

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)

In [79]:
print("Original Array:")
print(a)

Original Array:
[100 500  83  17  99  84  75  16  19  77   1  35  92  88  88]


In [81]:
print(np.delete(a, [0, 2, 4])) # Temporary Change

[500  17  84  75  16  19  77   1  35  92  88  88]


## **Chapter 15:** **Set functions**
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [83]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
print("Array (M): ")
print(m)
print()
print("Array (N): ")
print(n)

Array (M): 
[1 2 3 4 5]

Array (N): 
[3 4 5 6 7]


In [86]:
print("Union of Arrays m and n is: ")
print(np.union1d(m,n))
print()
print("Intersection of Arrays m and n is: ")
print(np.intersect1d(m,n))
print()
print("Difference of Arrays m and n is: ")
print(np.setdiff1d(m,n))
print()
print("Symmetric Difference of Arrays m and n is: ")
print(np.setxor1d(m,n))
print()
print("Is m in n: ")
print(np.in1d(m,n))

Union of Arrays m and n is: 
[1 2 3 4 5 6 7]

Intersection of Arrays m and n is: 
[3 4 5]

Difference of Arrays m and n is: 
[1 2]

Symmetric Difference of Arrays m and n is: 
[1 2 6 7]

Is m in n: 
[False False  True  True  True]


## **Chapter 16:** `numpy.clip()`

numpy.clip() function is used to Clip (limit) the values in an array.

[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.clip.html)

In [87]:
print("Original Array:")
print(a)

Original Array:
[100 500  83  17  99  84  75  16  19  77   1  35  92  88  88]


In [88]:
print("Clipping: ")
print(np.clip(a,a_min=25,a_max=75))

Clipping: 
[75 75 75 25 75 75 75 25 25 75 25 35 75 75 75]


## **Chapter 17:** `numpy.corrcoef()`

Return Pearson product-moment correlation coefficients.

The relation lies in between [-1, 1]

**NOTES:**
- +1 indicates a perfect positive linear relationship: as one variable increases, the other also increases in a perfectly predictable way.
- -1 indicates a perfect negative linear relationship: as one variable increases, the other decreases in a perfectly predictable way.
- 0 indicates no linear relationship: changes in one variable do not predict changes in the other.



[Documentation](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html)

In [63]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [64]:
print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


Some more functions try to learn yourself:
- `np.swapaxes`
- `np.count_nonzero`
- `np.uniform`
- `np.tile`
- `np.repeat`
- `np.allclose`
- `np.equals`