In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv('/content/customer.csv')

In [17]:
df.sample(5)

age  gender   review education purchased
48   39  Female     Good        UG       Yes
42   30  Female     Good        PG       Yes
41   23    Male     Good        PG       Yes
37   94    Male  Average        PG       Yes
36   34  Female     Good        UG       Yes

In [18]:
df = df.iloc[:,2:]

In [19]:
df.head(5)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size = 0.2)

In [21]:
X_train

review education
17     Poor        UG
24  Average        PG
3      Good        PG
30  Average        UG
46     Poor        PG
40     Good    School
49     Good        UG
42     Good        PG
33     Good        PG
1      Poor        UG
38     Good    School
32  Average        UG
35     Poor    School
10     Good        UG
2      Good        PG
47     Good        PG
48     Good        UG
0   Average    School
16     Poor        UG
26     Poor        PG
20  Average    School
22     Poor        PG
12     Poor    School
7      Poor    School
31     Poor    School
8   Average        UG
4   Average        UG
21  Average        PG
15     Poor        UG
25     Good    School
39     Poor        PG
34  Average    School
27     Poor        PG
41     Good        PG
19     Poor        PG
23     Good    School
36     Good        UG
14     Poor        PG
18     Good    School
29  Average        UG

# Ordinal Encoder

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
oe = OrdinalEncoder(categories = [['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [24]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [25]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [27]:
print("X-train: ")
print(X_train)
print("--------------------")
print("X-test: ")
print(X_test)

X-train: 
[[0. 1.]
 [1. 2.]
 [2. 2.]
 [1. 1.]
 [0. 2.]
 [2. 0.]
 [2. 1.]
 [2. 2.]
 [2. 2.]
 [0. 1.]
 [2. 0.]
 [1. 1.]
 [0. 0.]
 [2. 1.]
 [2. 2.]
 [2. 2.]
 [2. 1.]
 [1. 0.]
 [0. 1.]
 [0. 2.]
 [1. 0.]
 [0. 2.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 2.]
 [0. 1.]
 [2. 0.]
 [0. 2.]
 [1. 0.]
 [0. 2.]
 [2. 2.]
 [0. 2.]
 [2. 0.]
 [2. 1.]
 [0. 2.]
 [2. 0.]
 [1. 1.]]
--------------------
X-test: 
[[0. 0.]
 [2. 0.]
 [2. 1.]
 [1. 0.]
 [1. 2.]
 [1. 1.]
 [1. 0.]
 [0. 2.]
 [2. 1.]
 [0. 2.]]


In [28]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoder
The last column of the Purchase is in the categorical form we need to convert it into the label or numerical value.

Label encoding is explicitly used when you are working with the output columns.

Encode target labels with the value range between `[0 to n_classes-1]`

This transformer should be uswed to encode the target_values i.e. `Y` and not the input `X`.

In [29]:
from sklearn.preprocessing import LabelEncoder

In [32]:
le = LabelEncoder()

In [33]:
le.fit(y_train)

LabelEncoder()

In [34]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [35]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [36]:
y_train

array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1])